// Flat config for ESLint 9 (the project has no build step; these are browser scripts).
module.exports = [
  {
    files: ["frontend/js/**/*.js", "**/*.js"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "module",
      globals: {
        window: "readonly",
        document: "readonly",
        navigator: "readonly",
        console: "readonly",
        fetch: "readonly",
        localStorage: "readonly",
        sessionStorage: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        setInterval: "readonly",
        clearInterval: "readonly",
        requestAnimationFrame: "readonly",
        cancelAnimationFrame: "readonly",
        IntersectionObserver: "readonly",
        ResizeObserver: "readonly",
        MutationObserver: "readonly",
        AbortController: "readonly",
        URL: "readonly",
        URLSearchParams: "readonly",
        Image: "readonly",
        location: "readonly",
        history: "readonly",
        matchMedia: "readonly",
        getComputedStyle: "readonly",
        L: "readonly",
        gsap: "readonly",
        ScrollTrigger: "readonly",
        module: "writable",
        require: "readonly",
        process: "readonly",
      },
    },
    rules: {},
  },
];
