"""Allowlisted newsroom sources.

Every entry here was checked with a real HTTP request. Sources whose publisher offers no
lawful / working RSS, Atom or public API endpoint are listed in DISABLED_SOURCES with the
reason, and are never fetched. Only hostnames present in ALLOWED_HOSTS are ever requested.
"""

CATEGORIES = [
    "ART",
    "EXHIBITIONS",
    "GALLERIES_AND_MUSEUMS",
    "ARCHITECTURE_AND_DESIGN",
    "CONSTRUCTION",
    "URBAN_TRANSFORMATION",
    "KADIKOY",
    "TECHNICAL_AND_LEGAL",
]

# key, publisher, feed url, language, region, default category, editorial area, weight
SOURCES = [
    {
        "key": "hyperallergic",
        "name": "Hyperallergic",
        "url": "https://hyperallergic.com/feed/",
        "language": "en",
        "region": "INTERNATIONAL",
        "default_category": "ART",
        "area": "CULTURE",
        "weight": 3,
        "enabled": True,
    },
    {
        "key": "guardian-art",
        "name": "The Guardian — Art & Design",
        "url": "https://www.theguardian.com/artanddesign/rss",
        "language": "en",
        "region": "INTERNATIONAL",
        "default_category": "ART",
        "area": "CULTURE",
        "weight": 4,
        "enabled": True,
    },
    {
        "key": "artnet-news",
        "name": "Artnet News",
        "url": "https://news.artnet.com/feed",
        "language": "en",
        "region": "INTERNATIONAL",
        "default_category": "ART",
        "area": "CULTURE",
        "weight": 3,
        "enabled": True,
    },
    {
        "key": "colossal",
        "name": "Colossal",
        "url": "https://www.thisiscolossal.com/feed/",
        "language": "en",
        "region": "INTERNATIONAL",
        "default_category": "ART",
        "area": "CULTURE",
        "weight": 2,
        "enabled": True,
    },
    {
        "key": "labiennale",
        "name": "La Biennale di Venezia",
        "url": "https://www.labiennale.org/en/rss.xml",
        "language": "en",
        "region": "INTERNATIONAL",
        "default_category": "EXHIBITIONS",
        "area": "CULTURE",
        "weight": 5,
        "enabled": True,
    },
    {
        "key": "dezeen",
        "name": "Dezeen",
        "url": "https://www.dezeen.com/feed/",
        "language": "en",
        "region": "INTERNATIONAL",
        "default_category": "ARCHITECTURE_AND_DESIGN",
        "area": "BUILT",
        "weight": 3,
        "enabled": True,
    },
    {
        "key": "designboom",
        "name": "designboom",
        "url": "https://www.designboom.com/feed/",
        "language": "en",
        "region": "INTERNATIONAL",
        "default_category": "ARCHITECTURE_AND_DESIGN",
        "area": "BUILT",
        "weight": 2,
        "enabled": True,
    },
    {
        "key": "archdaily",
        "name": "ArchDaily",
        "url": "https://feeds.feedburner.com/Archdaily",
        "language": "en",
        "region": "INTERNATIONAL",
        "default_category": "ARCHITECTURE_AND_DESIGN",
        "area": "BUILT",
        "weight": 3,
        "enabled": True,
    },
    {
        "key": "guardian-cities",
        "name": "The Guardian — Cities",
        "url": "https://www.theguardian.com/cities/rss",
        "language": "en",
        "region": "INTERNATIONAL",
        "default_category": "URBAN_TRANSFORMATION",
        "area": "BUILT",
        "weight": 4,
        "enabled": True,
    },
    {
        "key": "arkitera",
        "name": "Arkitera",
        "url": "https://www.arkitera.com/feed/",
        "language": "tr",
        "region": "TR",
        "default_category": "ARCHITECTURE_AND_DESIGN",
        "area": "BUILT",
        "weight": 4,
        "enabled": True,
    },
    {
        "key": "arkitektuel",
        "name": "Arkitektüel",
        "url": "https://www.arkitektuel.com/feed/",
        "language": "tr",
        "region": "TR",
        "default_category": "ARCHITECTURE_AND_DESIGN",
        "area": "BUILT",
        "weight": 2,
        "enabled": True,
    },
    {
        "key": "tmmob",
        "name": "TMMOB",
        "url": "https://www.tmmob.org.tr/rss.xml",
        "language": "tr",
        "region": "TR",
        "default_category": "TECHNICAL_AND_LEGAL",
        "area": "BUILT",
        "weight": 5,
        "enabled": True,
    },
    {
        "key": "aa-guncel",
        "name": "Anadolu Ajansı",
        "url": "https://www.aa.com.tr/tr/rss/default?cat=guncel",
        "language": "tr",
        "region": "TR",
        "default_category": "URBAN_TRANSFORMATION",
        "area": "BUILT",
        "weight": 4,
        "enabled": True,
    },
    {
        "key": "aa-ekonomi",
        "name": "Anadolu Ajansı",
        "url": "https://www.aa.com.tr/tr/rss/default?cat=ekonomi",
        "language": "tr",
        "region": "TR",
        "default_category": "CONSTRUCTION",
        "area": "BUILT",
        "weight": 4,
        "enabled": True,
    },
]

# Publishers that were checked and left disabled — no lawful/working feed or API.
DISABLED_SOURCES = [
    {"name": "Resmî Gazete", "reason": "no public RSS/Atom or API endpoint (site returns no feed); scraping not permitted"},
    {"name": "Çevre, Şehircilik ve İklim Değişikliği Bakanlığı", "reason": "no reachable feed endpoint"},
    {"name": "Kentsel Dönüşüm Başkanlığı", "reason": "no reachable feed endpoint"},
    {"name": "İstanbul Büyükşehir Belediyesi", "reason": "feed paths return 404/503"},
    {"name": "Kadıköy Belediyesi", "reason": "no feed endpoint (SPA returns HTML)"},
    {"name": "TÜİK", "reason": "no RSS endpoint (bulletin page returns HTML)"},
    {"name": "AFAD", "reason": "no RSS endpoint"},
    {"name": "Türkiye İMSAD", "reason": "no RSS endpoint (returns HTML)"},
    {"name": "Türkiye Müteahhitler Birliği", "reason": "no RSS endpoint (404)"},
    {"name": "Mimarlar Odası", "reason": "feed host unreachable from this environment"},
    {"name": "yapi.com.tr", "reason": "automated access blocked (Cloudflare 403)"},
    {"name": "emlakkulisi.com", "reason": "automated access blocked (Cloudflare 403)"},
    {"name": "İstanbul Modern / SALT / Arter / Pera / Sakıp Sabancı / Borusan Contemporary / İKSV / Istanbul Biennial", "reason": "no public RSS, Atom or syndication endpoint"},
    {"name": "Tate / MoMA / Louvre / Centre Pompidou / Art Basel", "reason": "no public feed endpoint available"},
    {"name": "The Art Newspaper", "reason": "advertised feed path returns 404"},
    {"name": "Frieze", "reason": "automated access blocked (403)"},
    {"name": "Reuters", "reason": "public RSS discontinued; syndication requires a licence"},
]

ALLOWED_HOSTS = sorted({
    "hyperallergic.com",
    "www.theguardian.com",
    "news.artnet.com",
    "www.thisiscolossal.com",
    "www.labiennale.org",
    "www.dezeen.com",
    "www.designboom.com",
    "feeds.feedburner.com",
    "www.archdaily.com",
    "www.arkitera.com",
    "www.arkitektuel.com",
    "www.tmmob.org.tr",
    "www.aa.com.tr",
})


def enabled_sources():
    return [s for s in SOURCES if s.get("enabled")]
