"""Assembles the-apartments-tac.html and its stylesheet from the East West system.

The page reuses East West's chrome (utility bar, navigation, menu, footer) and its
project-page layout rules, renamed into the tac- namespace and re-toned dark, so
East West itself is never touched.
"""
import pathlib
import re

root = pathlib.Path(__file__).resolve().parent.parent
fe = root / "frontend"
ew_html = (fe / "east-west.html").read_text(encoding="utf-8")
ew_css = (fe / "css" / "east-west.css").read_text(encoding="utf-8")
main = (root / "scripts" / "tac_main.html").read_text(encoding="utf-8")

HERO = '  <section class="ew-hero" id="top">'
FOOT = "  <!-- ============================= FOOTER"

chrome, rest = ew_html.split(HERO, 1)
footer = FOOT + rest.split(FOOT, 1)[1]

chrome = chrome.replace(
    '<title>The Residences East West | Nova Konut</title>',
    '<title>The Apartments Taç | Nova Konut</title>')
chrome = re.sub(
    r'<meta name="description"[^>]*>',
    '<meta name="description" content="The Apartments Taç — a secure 4+1 residential address offering 190 m² gross and 149 m² net in Selamiçeşme, Bağdat Caddesi, Istanbul." />',
    chrome, count=1)
chrome = chrome.replace('<meta name="theme-color" content="#0b0b0b" />',
                        '<meta name="theme-color" content="#050505" />')
chrome = chrome.replace(
    '  <link rel="preload" as="image" href="media/images/east-west/videos/ew-hero-poster.webp" type="image/webp" fetchpriority="high" />\n'
    '  <link rel="preload" as="video" href="media/images/east-west/videos/ew-hero-web.mp4" type="video/mp4" fetchpriority="high" />',
    '  <link rel="preload" as="image" href="media/video/tac/tac-construction-poster.jpg" type="image/jpeg" fetchpriority="high" />')
chrome = chrome.replace('<link rel="stylesheet" href="css/east-west.css" />',
                        '  <link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css" />\n'
                        '  <link rel="stylesheet" href="css/the-apartments-tac.css" />')
chrome = chrome.replace('<body class="page-project">', '<body class="page-project page-tac">')
assert 'the-apartments-tac.css' in chrome and 'page-tac' in chrome

scripts = re.findall(r'\n *<script[^>]*>.*?</script>|\n *<script[^>]*/>', footer, re.S)
footer = footer.replace('js/east-west.js',
                        'https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"></script>\n  <script src="js/the-apartments-tac.js')
assert 'the-apartments-tac.js' in footer, "east-west.js reference not found in tail"

out = chrome + main.rstrip() + "\n\n" + footer
(fe / "the-apartments-tac.html").write_text(out, encoding="utf-8")
print("the-apartments-tac.html written:", len(out.splitlines()), "lines;",
      len(scripts), "script tags carried over")

# ---------------- stylesheet: the East West project-page system, re-toned dark ----------------
css = ew_css.replace("ew-", "tac-").replace(".page-project", ".page-tac")
tone = [
    ("--tac-dark: #0a0a0a", "--tac-dark: #050505"),
    ("--tac-gold: #6f6243", "--tac-gold: #A79879"),
    ("--tac-cream: #f5f1ea", "--tac-cream: #F5F4EE"),
    ("--tac-grey: #888", "--tac-grey: #A7A39B"),
    ("--tac-line: #e6e2d8", "--tac-line: rgba(245, 244, 238, .16)"),
    ("background: #1a1a1a; color: #fff; border-color: #1a1a1a", "background: #A79879; color: #0B0B0A; border-color: #A79879"),
    ("background: var(--tac-cream)", "background: #1A1916"),
    ("background: #fff", "background: #050505"),
    ("background: white", "background: #11110F"),
    ("background: #f2ede4", "background: #11110F"),
    ("background: #faf6ee", "background: #11110F"),
    ("color: #1a1a1a", "color: #F5F4EE"),
    ("color: #2a2a2a", "color: #A7A39B"),
    ("color: #3a3a3a", "color: #A7A39B"),
    ("border-color: #1a1a1a", "border-color: #A79879"),
    ("border: 1px solid #1a1a1a", "border: 1px solid rgba(245, 244, 238, .2)"),
    ("border-bottom: 1px solid #ddd", "border-bottom: 1px solid rgba(245, 244, 238, .16)"),
    ("border: 1px solid #ddd", "border: 1px solid rgba(245, 244, 238, .16)"),
    ("border-top: 1px solid #eee", "border-top: 1px solid rgba(245, 244, 238, .12)"),
]
for a, b in tone:
    css = css.replace(a, b)

# unified Taç colour pass: primary text, secondary text, bronze
for a, b in (("#F5F4EE", "#F0EEE8"), ("#A7A39B", "#AAA69D"), ("#A79879", "#A99A7B")):
    css = css.replace(a, b)

header = ("/* =========================================================\n"
          "   The Apartments Taç — generated by scripts/build_tac.py from\n"
          "   css/east-west.css: same project-page system, tac- namespace,\n"
          "   dark Taç palette. Page-specific rules live at the end.\n"
          "   ========================================================= */\n")
overrides = (root / "scripts" / "tac_overrides.css").read_text(encoding="utf-8")
for a, b in (("#F5F4EE", "#F0EEE8"), ("#A7A39B", "#AAA69D"), ("#A79879", "#A99A7B")):
    overrides = overrides.replace(a, b)
(fe / "css" / "the-apartments-tac.css").write_text(header + css.split("*/", 1)[1].lstrip() + "\n" + overrides,
                                                   encoding="utf-8")
print("the-apartments-tac.css written")
